---
title: "sample_nfl_data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{sample_nfl_data}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(RouteIdentification)
library(readr)
library(tidyverse)
```

```{r data}
# # Use online sample data from big data bowl
# 
# # list all the files
# #tracking_files <- list.files(path = "Data/", pattern = "tracking_.*\\.csv")
# 
# # Load all the data
# routes_data <- 
#   # create the tibble with the file names
#   tibble(file_name = "https://raw.githubusercontent.com/nfl-football-ops/Big-Data-Bowl/master/Data/tracking_gameId_2017090700.csv") %>%
#   # read the data in nested
#   mutate(data = map(file_name, read_routes_from_csv)) %>%
#   dplyr::select(-file_name) %>% 
#   unnest(cols = c(data))
# 
# # transform our curves
# routes_data <-
#   routes_data %>%
#   mutate(row = row_number()) %>%
#   mutate(data = pmap(list(data, team, direction_left, line_of_scrimmage), 
#                      ~ cut_plays(..1) %>%
#                        flip_field(., ..2, ..3, ..4)),
#          n = map_dbl(data, nrow)) %>%
#   filter(n >= 2) %>%
#   # left side of field is TRUE
#   mutate(data_same_sideline = purrr::map(data, 
#                                          ~ mutate(., 
#                                                   sof = 160/6 > first(y),
#                                                   y = if_else(sof, 160/3 - y, y),
#                                                   y = y - first(y)
#                                          ) %>%
#                                            dplyr::select(-sof)))  %>%
#   arrange(row)
# 
# 
# routes_data <-
#   routes_data %>%
#   ungroup() %>%
#   select(-row)
# 
# 
# routes_data %>%
#   mutate(curve_num = row_number()) %>%
#   unnest(cols = c(data_same_sideline)) %>%
#   select(curve_num, x, y) %>%
#   fit_new_data(nfl_em_results) %>%
#   left_join(cluster_route_map, by = c("cluster_assigned" = "cluster"))



```
